version: '3.1'

services:

  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: teste
      MARIADB_USERNAME: teste
      MARIADB_PASSWORD: teste
      MARIADB_DATABASE: teste

