-- MySQL Script generated by MySQL Workbench
-- ter 07 jun 2022 12:48:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema iKatoo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema iKatoo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iKatoo` ;
USE `iKatoo` ;

-- -----------------------------------------------------
-- Table `iKatoo`.`AboutPage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iKatoo`.`AboutPage` (
  `Id` VARCHAR(20) NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `id_UNIQUE` (`Id` ASC) VISIBLE,
  UNIQUE INDEX `Title_UNIQUE` (`Title` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iKatoo`.`SkillsPage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iKatoo`.`SkillsPage` (
  `Id` VARCHAR(20) NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iKatoo`.`Skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iKatoo`.`Skills` (
  `Id` VARCHAR(20) NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `RankPercent` INT NOT NULL,
  `AboutPage_id` VARCHAR(20) NOT NULL,
  `SkillsPage_Id` VARCHAR(20) NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `idSkills_UNIQUE` (`Id` ASC) VISIBLE,
  UNIQUE INDEX `title_UNIQUE` (`Title` ASC) VISIBLE,
  INDEX `fk_Skills_AboutPage_idx` (`AboutPage_id` ASC) VISIBLE,
  INDEX `fk_Skills_SkillsPage1_idx` (`SkillsPage_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Skills_AboutPage`
    FOREIGN KEY (`AboutPage_id`)
    REFERENCES `iKatoo`.`AboutPage` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Skills_SkillsPage1`
    FOREIGN KEY (`SkillsPage_Id`)
    REFERENCES `iKatoo`.`SkillsPage` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iKatoo`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iKatoo`.`image` (
  `Id` VARCHAR(20) NOT NULL,
  `Source` VARCHAR(45) NOT NULL,
  `AlternativeText` VARCHAR(45) NULL,
  `AboutPage_Id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `id_UNIQUE` (`Id` ASC) VISIBLE,
  UNIQUE INDEX `Source_UNIQUE` (`Source` ASC) VISIBLE,
  INDEX `fk_image_AboutPage1_idx` (`AboutPage_Id` ASC) VISIBLE,
  CONSTRAINT `fk_image_AboutPage1`
    FOREIGN KEY (`AboutPage_Id`)
    REFERENCES `iKatoo`.`AboutPage` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iKatoo`.`ContactPage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iKatoo`.`ContactPage` (
  `Id` VARCHAR(20) NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(250) NOT NULL,
  `Localization` GEOMETRY NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  UNIQUE INDEX `Title_UNIQUE` (`Title` ASC) VISIBLE,
  UNIQUE INDEX `Description_UNIQUE` (`Description` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iKatoo`.`LastJobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iKatoo`.`LastJobs` (
  `Id` VARCHAR(20) NOT NULL,
  `YearMonthStart` VARCHAR(45) NOT NULL,
  `YearMonthEnd` VARCHAR(45) NULL,
  `JobTitle` VARCHAR(45) NOT NULL,
  `JobDescription` VARCHAR(250) NOT NULL,
  `SkillsPage_Id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  INDEX `fk_LastJobs_SkillsPage1_idx` (`SkillsPage_Id` ASC) VISIBLE,
  CONSTRAINT `fk_LastJobs_SkillsPage1`
    FOREIGN KEY (`SkillsPage_Id`)
    REFERENCES `iKatoo`.`SkillsPage` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iKatoo`.`ProjectsPage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iKatoo`.`ProjectsPage` (
  `Id` VARCHAR(20) NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iKatoo`.`Projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iKatoo`.`Projects` (
  `Id` VARCHAR(20) NOT NULL,
  `Snapshot` VARCHAR(45) NOT NULL,
  `GithubLink` VARCHAR(100) NULL,
  `Title` VARCHAR(45) NOT NULL,
  `YearMonthEnd` VARCHAR(45) NULL,
  `Description` VARCHAR(250) NOT NULL,
  `ProjectsPage_Id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  INDEX `fk_Projects_ProjectsPage1_idx` (`ProjectsPage_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Projects_ProjectsPage1`
    FOREIGN KEY (`ProjectsPage_Id`)
    REFERENCES `iKatoo`.`ProjectsPage` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
